### ISSUE TITLE
Ansible modules

### ISSUE THREAD

**Issue by bchamby** [thopper91/Ansible-HPE_Synergy_Config#1]
Hi @thopper91. Would you be able to push your /home/hoppert/oneview-ansible-3.1.1/library/ directory (ref: https://github.com/thopper91/Ansible-HPE_Synergy_Config/blob/master/ansible.cfg#L15) to this repo, so we can see your custom ansible modules?

Thanks,
Brad

**Comment by thopper91** [comment]
Hi @bchamby , sadly they weren't ansible custom modules. All I did was a repository pull from GitHub however as I was using multiple repositories for different projects, I just pointed the configuration to the correct modules. Hope that made sense? If you still want the url, I'm not sure what version they are on now but the repository is: https://github.com/HewlettPackard/oneview-ansible

Hopefully I didn't disappoint too much

**Comment by bchamby** [comment]
Ah, I did not see that repo on HP's github. This is perfect! Thank you very much.
